version: '{branch}_{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2019
shallow_clone: true
environment:
  LicensedDependenciesUrl:
    secure: ZTSg1DK6QAtwZoCBUDQ94cIaMCKWgSeJMI0dCpVJBPE40+UqG9MNu+UJjjGWjvVa
  OnlineInstallerConfig: https://playnite.link/build/installer_mirrors.txt
build_script:
- pwsh: .\build\build.ps1 -Package -SdkNuget -LicensedDependenciesUrl $env:LicensedDependenciesUrl -OnlineInstallerConfig $env:OnlineInstallerConfig
test: off
artifacts:
- path: 'build\Playnite.zip'
deploy:
- provider: GitHub
  tag: continuous
  release: continuous
  auth_token:
    secure: j2wYgDHRlxXaLB8MjsM3l2T+KlBA441m1r9g5cdo6nNh36f7w+iRlUv6eDtNB332
